version: '3.8'

services:

  db:
    image: mariadb:11
    container_name: vicko-homework-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: vicko
      MARIADB_USER: vicko
      MARIADB_PASSWORD: vicko123
    volumes:
      - ./db:/var/lib/mysql

  pma:
    image: phpmyadmin:latest
    container_name: vicko-homework-pma
    links:
      - db
    environment:
      PMA_HOST: vicko-homework-db
      PMA_PORT: 3306
    restart: always
    ports:
      - 8081:80

  php:
    container_name: vicko-homework-php
    build:
      context: ./php
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - db

  nginx:
    container_name: vicko-homework-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
